import { Product } from './types';

// NOTE: Updated with reliable Unsplash source URLs to ensure all images load correctly.

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Artisan Psychedelic Flat',
    price: 65,
    category: 'Lifestyle',
    sizes: [5, 6, 7, 8, 9],
    colors: ['Multi-color'],
    image: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=80',
    description: 'Vibrant and artistic slip-ons designed to make a statement. Features a comfortable sole and breathable fabric with a unique swirl pattern.',
    isFeatured: true,
  },
  {
    id: '2',
    name: 'Air Max Golden Era',
    price: 160,
    category: 'Running',
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Gold/Red'],
    image: 'https://images.unsplash.com/photo-1584735175097-719d848f8449?auto=format&fit=crop&w=800&q=80',
    description: 'A classic silhouette reimagined in striking gold with red accents. Features premium air-cushioning for all-day performance.',
    isFeatured: true,
  },
  {
    id: '3',
    name: 'Heritage Leather Boot',
    price: 210,
    category: 'Lifestyle',
    sizes: [8, 9, 10, 11, 12],
    colors: ['Brown'],
    image: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=800&q=80',
    description: 'Timeless brown leather boots with durable construction. Perfect for smart-casual urban wear or lighter trails.',
    isFeatured: false,
  },
  {
    id: '4',
    name: 'Retro Wave Trainer',
    price: 110,
    category: 'Lifestyle',
    sizes: [6, 7, 8, 9, 10],
    colors: ['White/Teal/Yellow'],
    image: 'https://images.unsplash.com/photo-1555274175-75f4056dfd05?auto=format&fit=crop&w=800&q=80',
    description: '90s inspired chunky trainer featuring a mix of suede and mesh in cool teal and yellow tones.',
    isFeatured: true,
  },
  {
    id: '5',
    name: 'Classic Canvas Low',
    price: 80,
    category: 'Lifestyle',
    sizes: [5, 6, 7, 8, 9, 10, 11],
    colors: ['Black/White'],
    image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=800&q=80',
    description: 'The iconic canvas sneaker in black. Versatile, durable, and always in style. A staple for every wardrobe.',
    isFeatured: false,
  },
  {
    id: '6',
    name: 'Zoom Fly Salmon',
    price: 145,
    category: 'Running',
    sizes: [7, 8, 9, 10, 11],
    colors: ['Salmon/Black'],
    image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=800&q=80',
    description: 'Lightweight breathable mesh in a standout salmon colorway. Designed for speed and responsiveness on the track.',
    isFeatured: true,
  },
  {
    id: '7',
    name: 'Street Flame Skater',
    price: 95,
    category: 'Lifestyle',
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Black/Flame'],
    image: 'https://images.unsplash.com/photo-1521093470119-a3acdc43374a?auto=format&fit=crop&w=800&q=80',
    description: 'Ignite your style with these flame-print skate shoes. Suede and canvas upper for durability on the board.',
    isFeatured: true,
  },
  {
    id: '8',
    name: 'Court Legacy Blue',
    price: 100,
    category: 'Lifestyle',
    sizes: [8, 9, 10, 11, 12],
    colors: ['Blue/White'],
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
    description: 'Clean lines and retro tennis vibes. Deep blue leather with a crisp white swoosh and classic gum sole.',
    isFeatured: false,
  },
  {
    id: '9',
    name: 'Sky High Teal',
    price: 190,
    category: 'Basketball',
    sizes: [9, 10, 11, 12, 13, 14],
    colors: ['Teal/White'],
    image: 'https://images.unsplash.com/photo-1575537302964-96cd47c06b1b?auto=format&fit=crop&w=800&q=80',
    description: 'High-top basketball sneakers in a refreshing teal and white colorway. Legendary performance and ankle support.',
    isFeatured: true,
  },
  {
    id: '10',
    name: 'Sunset Racer',
    price: 130,
    category: 'Running',
    sizes: [6, 7, 8, 9, 10],
    colors: ['Orange/White'],
    image: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=800&q=80',
    description: 'Bright orange nylon upper for a retro running look. Lightweight foam midsole provides essential comfort.',
    isFeatured: false,
  },
  {
    id: '11',
    name: 'Indigo Denim Runner',
    price: 125,
    category: 'Lifestyle',
    sizes: [7, 8, 9, 10, 11],
    colors: ['Denim Blue'],
    image: 'https://images.unsplash.com/photo-1596568359553-a56de6970068?auto=format&fit=crop&w=800&q=80',
    description: 'Unique denim-inspired textile upper. A fusion of casual jeans style and athletic comfort.',
    isFeatured: false,
  },
  {
    id: '12',
    name: 'Concrete Jungle Mid',
    price: 185,
    category: 'Basketball',
    sizes: [8, 9, 10, 11, 12, 13],
    colors: ['Grey/White'],
    image: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80',
    description: 'Versatile grey and white colorway. Premium leather construction for the courts or the streets.',
    isFeatured: true,
  }
];

export const MOCK_USER = {
  id: 'u1',
  name: 'Alex Walker',
  email: 'alex@walkin.it',
  role: 'admin' as const
};